### ISSUE TITLE
test_run() takes exactly 3 arguments (1 given) in flaskr.py

### ISSUE THREAD

**Issue by Vaishnavi-Chilukuri** [chen0040/keras-question-and-answering-web-api#1]
While running qa_system_web/flaskr.py I am getting the following error
File "flaskr.py", line 48, in <module>
    main()
  File "flaskr.py", line 43, in main
    squad_s2s_qa.test_run()
TypeError: test_run() takes exactly 3 arguments (1 given)

**Comment by chen0040** [comment]
@Vaishnavi-Chilukuri Thanks for reporting the issue, I have fixed the problem and testing the application by running within PyCharm.

**Comment by chen0040** [comment]
@Vaishnavi-Chilukuri I am currently refactoring the codes to make it easier to use, the refactored codes are in the demo and keras_question_and_answering_system and should not affect the current system as it is

**Comment by Vaishnavi-Chilukuri** [comment]
Thanks for your update. Can you please let me know the number of epochs you have used to train the model?

**Comment by chen0040** [comment]
For the older model in deprecated folder (those that are before the refactoring yesterday), as it was some time ago and i did not save history, i cannot quite remember, but my guess is around 10 epochs. For the refactoring version, I did a training with gpu for squad_seq2seq_train.py using 100 epochs and batch_size = 64, but i have not uploaded the retrained model for the refactored version yet as the training is still running on my computer.

**Comment by chen0040** [comment]
I have now managed to train the refactored codes using squad_seq2seq_train.py for 200 epochs (actually after 100 epochs the predict result looks good enough, but i ran 200 epochs to test the convergence). The trained model can be found in demo/models and you can run squad_seq2seq_predict.py to see the result (i have also updated the ReadMe.md) by including the output print out from running squad_seq2seq_predict.py
